services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: roxiler
      POSTGRES_PASSWORD: roxiler
      POSTGRES_DB: roxiler
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/scripts/create-test-db.sql:/docker-entrypoint-initdb.d/create-test-db.sql:ro
volumes:
  pgdata:
